### ISSUE TITLE
Close doesn't close stream

### ISSUE THREAD

**Issue by sksamuel** [monitorjbl/excel-streaming-reader#1]
The close method doesn't close anything, but just deletes the tmp file.
What happens to the input stream here: https://github.com/monitorjbl/excel-streaming-reader/blob/master/src/main/java/com/monitorjbl/xlsx/StreamingReader.java#L276 ?

**Comment by monitorjbl** [comment]
Good catch! The `parser` field just needs to be closed in the `close()` method.

**Comment by monitorjbl** [comment]
This should be fixed in the 0.2.4 release. Give it a shot and let me know if it's working for you!

**Comment by sksamuel** [comment]
Great thanks.
