### ISSUE TITLE
Licence incompatiblity 

### ISSUE THREAD

**Issue by matthiasblaesing** [monitorjbl/excel-streaming-reader#10]
I noticed that you decided to choose the GPLv2 for your library, while I consider this licence in general fair, in this case it could pose issues - according to the FSF GPLv2 and APLv2 are incompatible:

http://www.gnu.org/licenses/license-list.en.html#apache2

As this is build on top of apache POI I would suggest to move to APLv2 as the basic library.

Please note: I'm not a lawyer, I was just stumbling over the project because saw my heap explode when reading a small excel file.

**Comment by monitorjbl** [comment]
Yeah, I'm no lawyer either, I basically read a cliff notes version of the most popular licenses and picked the one that had the most "open" feel to it. Thanks for the tip, I'll do some research and see what the options are.

**Comment by monitorjbl** [comment]
Updated license to Apache 2.0,

**Comment by matthiasblaesing** [comment]
Thank you very much!
