### ISSUE TITLE
temp files have not be deleted

### ISSUE THREAD

**Issue by neal1991** [monitorjbl/excel-streaming-reader#114]
I have found the temp files of reading xlsx files, the created temp- files have not been deleted at all. They are all kept in your temp folder inside your PC.
I think it's really a serious problem!!!!!!!!

**Comment by monitorjbl** [comment]
You closed the issue, did you not think it was a bug anymore? This library should clean up after itself as long as it runs to completion. If you abort execution early with a `kill` command then that isn't guaranteed, but in any other case it should remove the temp file when you close the reader.

**Comment by neal1991** [comment]
@monitorjbl I have to close the workbook manually to delete temp files.

**Comment by Dimitri1205** [comment]
I had a similar problem, temp file would not be deleted even if I closed the workbook. I was getting the file from urlConnection.getInputStream().  I had to close the inputStream first and then close the workbook. Maybe it will help someone who encounters it.
