### ISSUE TITLE
the difference between read file and inpustream

### ISSUE THREAD

**Issue by neal1991** [monitorjbl/excel-streaming-reader#124]
It is recommended to open file instead of opening inpustream in POI. So is it same in excel-streaming-reader. I try to open file instead of inpustream, is this a better solution? I have come across the problem that open xlsx file outofmemory.

**Comment by monitorjbl** [comment]
There's no difference with this library. It buffers the inputstream to a file.

**Comment by neal1991** [comment]
So, actually this library is still loading the inputstream when open a file? For the sake of memory, I have seen that open a file is better solution to avoid loading inpustream at one time. So it is different here?
It will not be better to open a file instead of inputstram, isn't it?

**Comment by monitorjbl** [comment]
This library is designed to keep memory overhead to a minimum. If you load from an inputstream, the entire stream will be buffered to a file before this library begins parsing it. If load from a file, it will simply read the file and begin parsing it. 

There is no difference in memory usage at runtime, but if you have a large file and load it by inputstream it may take some time to buffer at the beginning.

**Comment by monitorjbl** [comment]
I'm closing this issue but feel free to continue asking questions on it.
