### ISSUE TITLE
If you set an sstCacheSize then Cell contents are truncated after an '&' or a '<' or a '>' character.

### ISSUE THREAD

**Issue by cmpaine** [monitorjbl/excel-streaming-reader#136]
If you set an sstCacheSize (e.g: Workbook workbook = StreamingReader.builder().sstCacheSize(100).open(excelInputStream); ),
then if you have a cell with text in it that contains a '&' or a '<' or a '>' character, then the cell contents returned by cell.getStringCellValue() only has the text before that character: i.e if a cell contains "A & B", then cell.getStringCellValue() returns "A ".

**Comment by boboetuk** [comment]
What is the version you are using and can you provide an example file that can reproduce the issue. 
I failed to simulate the problem with the described data. 
Tried "A & B", "A & B <C><D>" and "A & B > C < D"

**Comment by cmpaine** [comment]
[AmpersandExample.xlsx](https://github.com/monitorjbl/excel-streaming-reader/files/1737424/AmpersandExample.xlsx)

I am using version 1.2.0.

In only happens if you set an sstCacheValue, like this:
Workbook workbook = StreamingReader.builder().sstCacheSize(100).open(excelInputStream);

**Comment by boboetuk** [comment]
I see this problem is fixed in the latest version 1.2.1
https://github.com/monitorjbl/excel-streaming-reader/pull/105
I tried your file with it and it works as expected

**Comment by cmpaine** [comment]
Yes, using version 1.2.1 fixed the problem. Thanks.
