### ISSUE TITLE
getDateCellValue not working as desired.

### ISSUE THREAD

**Issue by rupeshpadhye** [monitorjbl/excel-streaming-reader#14]
I am reading an excel's column whose format is Date.
row.getCell(54).getCellType()  -->(showing 3)
row.getCell(54).getDateCellValue() ;
giving me Following Runtime Exception.
Exception in thread "main" java.lang.NullPointerException
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.monitorjbl.xlsx.impl.StreamingCell.getNumericCellValue(StreamingCell.java:130)
	at com.monitorjbl.xlsx.impl.StreamingCell.getDateCellValue(StreamingCell.java:143)

**Comment by monitorjbl** [comment]
Judging from the stacktrace, the cell value is null when that error occurs. There should always be an error in that case (though it could certainly be made clearer). Are you sure the sheet has a value there? If so, can you post an example file?

**Comment by rupeshpadhye** [comment]
Yes you are correct .The cell value is empty.So how one can handle this scenario.I think currently this method is not able to handle null condition.

**Comment by monitorjbl** [comment]
Looks like the way I wrote this technically violates the terms of the interface:

```
java.util.Date getDateCellValue()
    Get the value of the cell as a date. For strings we throw an exception. For blank cells we return a null.

double getNumericCellValue()
    Get the value of the cell as a number. For strings we throw an exception. For blank cells we return a 0. For formulas or error cells we return the precalculated value;
```

So, it should just return a null unless the value is not parseable.
