### ISSUE TITLE
It would be realy helpful if you can add shiftRows() Function

### ISSUE THREAD

**Issue by Chandan1si13is016** [monitorjbl/excel-streaming-reader#140]
Since this is such a good API it would be awesome to see shiftRows() function. It will cover all aspects of excel sheet.

**Comment by monitorjbl** [comment]
This library cannot support writes to worksheets. It is a reader only; writes would require a lot more memory and the full POI library already does this. I'm afraid you're stuck using vanilla POI if you need to modify a sheet.

**Comment by monitorjbl** [comment]
I'm going to close this issue as it's asking for functionality that cannot be provided. If you have any more questions, I'm happy to answer them.
