### ISSUE TITLE
Way to iterate over all sheets

### ISSUE THREAD

**Issue by Schattensilber** [monitorjbl/excel-streaming-reader#16]
As it stands (and as I understand it) this tool is not useful for reading in a multi sheet workbook with an unknown number of sheets.
Is it possible to include a method to change that? Ideally getAllSheetNames(), but also getNumberOfSheets() or hasSheet(int index) would enable iterating over all sheets.

**Comment by monitorjbl** [comment]
I think this is a good idea, but would require a compatibility-breaking refactor of the current codebase to do properly because I don't want to just bolt this on. Rather than StreamingReader being like the Sheet and giving you Rows it would be the Workbook and you'd get Sheets out of it. 

Does that work for you?

**Comment by Schattensilber** [comment]
Sounds great, this way it would be even closer to the XSSFWorkbook structure, but with sheet iteration. For my purposes it would be important to get the sheet names. If that's all in then this could go into POI as the SXSSF sidekick for reading :)

**Comment by endriju** [comment]
+1 for supporting multi sheet workbooks, would be very useful

**Comment by monitorjbl** [comment]
@endriju @Schattensilber There is an implementation available in the 0.3 branch that allows you to stream an entire workbook with all of its sheets. I'm trying to keep it backwards-compatible, so apologies if the options are a little confusing at the moment. I'll give it another pass soon to clean things up.

**Comment by monitorjbl** [comment]
This has been added to mainline codebase and is now available in version 1.0.0 from Maven Central.
