### ISSUE TITLE
Getting an error "java.lang.ClassNotFoundException: org.apache.poi.util.StaxHelper"

### ISSUE THREAD

**Issue by RahulMetangale** [monitorjbl/excel-streaming-reader#168]
Hi,

I am trying  to use this library to stream excel stored in Azure Blob storage. I added following jars to my project:
xlsx-streamer-1.2.1.jar
xmlbeans-2.6.0.jar
stax-api-1.0.2.jar
poi-3.12.jar
poi.ooxml-3.12.jar
poi-ooxml-schemas-3.12.jar

While running the application i am getting an error "java.lang.ClassNotFoundException: org.apache.poi.util.StaxHelper". Under org.apache.poi.util i do not see StaxHelper. 

Any pointer to resolve this issue?

Thanks,
Rahul

**Comment by pjfanning** [comment]
You need to use an up to date copy of the poi jars. 3.17 with the last xlsx-streamer release and 4.0.0 with the latest code on github.

**Comment by RahulMetangale** [comment]
Thank you!

That helped in resolving the issue.
