### ISSUE TITLE
Getting exception while creating cellstyle

### ISSUE THREAD

**Issue by mnomansadiq** [monitorjbl/excel-streaming-reader#180]
I am getting a problem when open a workbook and create style on a cell this give me an exception like this:
com.monitorjbl.xlsx.impl.StreamingWorkbook.createCellStyle(StreamingWorkbook.java:275)

Here is my code:
        try (InputStream is = new FileInputStream(excelFile);
             Workbook workbook = StreamingReader.builder()
                     .rowCacheSize(100).bufferSize(4096).open(is)) {
  
   CellStyle dateCellStyle = workbook.createCellStyle();
   dateCellStyle.setDataFormat((short) 14);
}

Is setting style is not supported in this library ?

**Comment by monitorjbl** [comment]
No, this is a read-only library. You cannot modify the worksheet in any way.
