### ISSUE TITLE
2.1.0 NullPointerException when loading a large file (70 columns, 250,000 rows) with a large number of blank cells using sst cache.

### ISSUE THREAD

**Issue by texhnolyzze** [monitorjbl/excel-streaming-reader#198]

**Comment by pjfanning** [comment]
@texhnolyzze would you be able to share your xlsx file?

I have a [fork](https://github.com/pjfanning/excel-streaming-reader) and I use a different SST implementation. If you can't share your xlsx, could you try it with my lib to see if it handles your file ok?
