### ISSUE TITLE
Tmp file are not deleted if sheet not found.

### ISSUE THREAD

**Issue by jeancl** [monitorjbl/excel-streaming-reader#2]
If i call read by InputStream a tmp file will be created.

Ok, but if sheet was not found the result is a RuntimeException and the tmp file will not be deleted and StreamingReader does not will be returned to let me call close method.

It will occur not only when sheet = null, if take any exception in read by file the tmp file will be let in temp folder from filesystem.

**Comment by monitorjbl** [comment]
Ah, I see. I'll get that fixed when I get off work. I'll also have that code throw a more meaningful exception type.

**Comment by monitorjbl** [comment]
Just released a new version to Maven Central with the fix. Let me know if you're seeing a temp file hanging around.

**Comment by jeancl** [comment]
Perfect it solves.

But i think, you can can make these calls to f.delete() parameterized (.deleteFileOnError(true|false)) like your params of buffer size.

Because to my case i want to delete malformed files provided by ImputStream, but the public method read(File f) can be reciving an direct (and very important) file from consumer aplication and if it get an exception this file will be deleted.

I do not want you to be cursed because of me. If any developer pass an important file directly and put a wrong sheet name accidentally. 

In advanced. Thanks for fast response. 
Great Job...

**Comment by monitorjbl** [comment]
Oh jeez, I see what you mean. I'll get that fixed right away.

**Comment by monitorjbl** [comment]
Released a new version to Maven Central with that issue resolved and a unit test to make sure the `read(File)` option doesn't delete anything it shouldn't.

**Comment by jeancl** [comment]
Yeah all right now.

Thanks again...
closing issue...
