### ISSUE TITLE
NullPointerException when cell type is null

### ISSUE THREAD

**Issue by DraculaLei** [monitorjbl/excel-streaming-reader#24]
source code line 123,when type is null

Exception in thread "main" java.lang.NullPointerException
	at com.monitorjbl.xlsx.StreamingReader.unformattedContents(StreamingReader.java:216)
	at com.monitorjbl.xlsx.StreamingReader.handleEvent(StreamingReader.java:136)
	at com.monitorjbl.xlsx.StreamingReader.getRow(StreamingReader.java:89)

[datetest.xlsx.zip](https://github.com/monitorjbl/excel-streaming-reader/files/103057/datetest.xlsx.zip)

**Comment by monitorjbl** [comment]
What version are you using?

**Comment by monitorjbl** [comment]
I think this particular bug was fixed in 0.2.11

**Comment by DraculaLei** [comment]
yes it was fixed,but the patch lead to another bug，when the type is null and the cellStringvalue is not equal the orinal value show in excel。
i think the cell type is ‘n’ as default，because when i set the cell type as ‘n’，the cellStringValue is right。
and from the poi ‘s source code，when the type is null，it will always be the default type

**Comment by monitorjbl** [comment]
Just tried a simple test and I'm not seeing any errors with the latest version:

```
  @Test
  public void testNullTypes() throws Exception {
    try(
        InputStream is = new FileInputStream(new File("src/test/resources/nulltypes.xlsx"));
        StreamingReader reader = StreamingReader.builder().read(is);
    ) {
      for(Row r : reader) {
        for(Cell c : r) {
          assertNotNull(c.getStringCellValue());
          System.out.println(c.getStringCellValue());
        }
      }
    }
  }
```

Can you give me an example of what you were trying to do when you hit this error? Also, can you make doubly sure that you're on the latest version? Line 216 is not a valid line of code in `StreamingReader` in 0.2.11 (the latest version), but it was in 0.2.10 (previous version).

**Comment by lilyliuce** [comment]
I also run the test with the given file. But I think what DraculaLei meant what that the output Value is different from the value of Column F and J in the file "datetest.xlsx". 
For example, instead of outputing "8:00:00", "0.33333333333333298" would be outputed. 
This can be fixed by changing the code as blow:
--StreamingReader.java line 128
        if(type != null) {
          currentCell.setType(type.getValue());
        } else {
          currentCell.setType("n");
        }
--StreamingReader.java line 193 and line 223:
        switch(currentCell.getType()) 

But I am having trouble at getting the right value of the Column A.
The output is "42339" instead of "平成27年12月1日".

**Comment by DraculaLei** [comment]
I also fixed  the problem as lilyliuce ...
I think the output of  "平成27年12月1日" is right....
The output depends on your locate when the cell's sytle is customed just like my output is "12月1日" the same string as excel

**Comment by lilyliuce** [comment]
Alright, then. I will add the patch.
