### ISSUE TITLE
New release planned with Apache POI 5.x (4.1.2 contains vulnerabilities)?

### ISSUE THREAD

**Issue by f1zb4n** [monitorjbl/excel-streaming-reader#241]
As Apache POI 4.1.2 contains several vulnerabilities and excel-streaming-reader is still using this version, I would like to ask if there is a new release planned?

Thanks

**Comment by ascrus** [comment]
Hi. There is a rewritten version that uses POI 5 and adds functionality:
https://github.com/pjfanning/excel-streaming-reader
