### ISSUE TITLE
Not returning empty cells

### ISSUE THREAD

**Issue by darkman97i** [monitorjbl/excel-streaming-reader#34]
In my xlsx file I have some empty cells what are not returned, simply I'm getting the next cell. That cause I can not be sure about which column is really returning to me. 

I do not know which is the internal logic, but will be better if I can tell how many columns I want to be returned rather jumping empty cells.

**Comment by Aguinore** [comment]
Unfortunately, it's unavoidable. Empty cells are simply not mentioned in XML inside .xlsx file (which is simple zip-archive), so every iterator skips them. Also it skips empty rows as well. The only way is to go with index from 0 to sheet.lastRowNum and from 0 to row.lastCellNum in every row, but you lose stream benefits.

**Comment by darkman97i** [comment]
Understood, thanks for your answers

**Comment by NiharGharat** [comment]
> Unfortunately, it's unavoidable. Empty cells are simply not mentioned in XML inside .xlsx file (which is simple zip-archive), so every iterator skips them. Also it skips empty rows as well. The only way is to go with index from 0 to sheet.lastRowNum and from 0 to row.lastCellNum in every row, but you lose stream benefits.

@Aguinore  I was trying to get complete sheet data, including all empty rows and columns as null. I am using a pointer variables to detect iterator skip(same as apache poi), but row.getRowNum() and colIndex do not give any skip in their values for completely empty row and column. How do you detect a skip?
