### ISSUE TITLE
Can't delete delete file used by StreamingReader

### ISSUE THREAD

**Issue by cesartl** [monitorjbl/excel-streaming-reader#39]
Hi,

When I use the `StreamingReader` with a manual file it cannot be deleted. In windows it complains that the file is used by another process:

    final File source = new File("\some\file.xlsx");
    final File tmp = Files.createTempFile("tmp-", ".xlsx").toFile();
    FileUtils.copyFile(source, tmp); //this is Apache-commons-IO but it doesnt' really matter how we produced the temp file, the problem is the same
    System.out.println(tmp.getCanonicalPath());
    try(StreamingReader reader = StreamingReader.builder().sheetIndex(0).read(tmp)){
        for (Row row : reader) {
            //do something
        }
    }
    Files.delete(tmp.toPath()); //throws an exception

Looking at the StreamingReader code I see that you are creating a `OPCPackage`, shouldn't it be closed when the `StreamingReader` is closed? Is it something else? Are you able to reproduce this?

Thanks,

Cesar,

PS: Great library btw!

**Comment by monitorjbl** [comment]
To be honest, I haven't really tested much on Windows. I know it's a lot weirder about file locking than *nix filesystems though, so I guess I just never noticed this issue before. 

You're likely correct that a stream just needs to be closed. I'll take a look.

**Comment by monitorjbl** [comment]
@cesartl Can you give the latest code a try on Windows? I added a `revert()` call to close the `OPCPackage` without saving.

**Comment by cesartl** [comment]
Hi, the same test now passes. Thanks!

**Comment by monitorjbl** [comment]
0.2.13 has been released to Maven Central, so you should be able to use that version now.

**Comment by Chandan1si13is016** [comment]
Hi do we have remove row functionality for excel sheet using StreamingReader
