### ISSUE TITLE
Reader returning additional blank lines

### ISSUE THREAD

**Issue by martonp** [monitorjbl/excel-streaming-reader#4]
As I am iterating through an excel file, the module returns a blank row every 1 + cacheSize rows. When I set the cache size to 10 rows, I get an extra blank row every 11 rows, and when I set the cache size to 100 rows I get a blank row every 101 rows. Do you have any idea what might be causing this?

**Comment by monitorjbl** [comment]
That's interesting, it's a bug with the streamer. It always adds the current row being processed, even if the event hasn't created a new one I guess since the original project I wrote this for had to ignore blank rows anyway I never noticed this going on. I'll push out a fix right away.
