### ISSUE TITLE
Unable to read input stream

### ISSUE THREAD

**Issue by raboonveeva** [monitorjbl/excel-streaming-reader#42]
> got java.io.IOException: Stream Closed
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:233)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.writeInputStreamToFile(StreamingWorkbookReader.java:170)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:74)

`public static void readExcelFileAsStreamer(File excelFile, List<String> header, Queue<Row> rows, Status status) {

        boolean foundSheet = false;
        int hdrRowPos = -1;
        int sheetPos = -1;
        int rowLimit = 10;
        int count = 0;
        int totalRowCounter = 0;
        StreamingReader reader = null;
        Iterator<Row> rowIterator = null;
        Row headerRow = null;
        try {
            status.init();
            InputStream is = new FileInputStream(excelFile);

            // ########################################### Find sheet and header row ###############################
            for (int i = 0; i < rowLimit && !foundSheet; i++) {
                Workbook workbook = StreamingReader.builder()
                        .rowCacheSize(100)    // number of rows to keep in memory (defaults to 10)
                        .bufferSize(16384)     // buffer size to use when reading InputStream to file (defaults to 1024)
                        .sheetIndex(0)        // index of sheet to use (defaults to 0)
                        .open(is);   
                Sheet  sheet= workbook.getSheetAt(0);
                rowIterator = sheet.iterator();

                while (rowIterator.hasNext() && count < rowLimit && !foundSheet) {
                    Row r = rowIterator.next();
                    count = r.getRowNum();
                    if (checkIfHeaderKeyExists(r)) {
                        foundSheet = true;
                        sheetPos = i;
                        headerRow = r;
                        hdrRowPos = count;
                        log.warn("For file: " + excelFile.getName() + " header key is found on Header position: " + hdrRowPos);
                    }

                }
            }
            // ############################################################################

            if (hdrRowPos == -1 || sheetPos == -1) {
                throw new IllegalArgumentException("Given File: " + excelFile + " is not a Valid file");
            }

            getHeaders(excelFile, header, headerRow);

            status.setLoadedHeader();
            Thread.sleep(5000);

            int emptyRowCount = 0;

            status.setReading();
            while (rowIterator.hasNext()) {
                Row r = rowIterator.next();

                if (r == null || isEmptyRowStrm(r, header)) {
                    log.warn("For file: " + excelFile + ", row: " + r.getRowNum() + " is empty");
                    emptyRowCount++;
                    if (emptyRowCount > MAX_EMPTY_ROW) {
                        log.warn("finsihed to end of excel file");
                        break;
                    }
                    continue;
                }
                if (r.getRowNum() % 1000 == 0) {
                    // log.info("Added Row: " + r.getRowNum());
                    //Thread.sleep(100);
                }
                if (r != null) {
                    totalRowCounter++;
                    rows.add(r);
                    emptyRowCount = 0;
                }

            }
            Thread.sleep(1000);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            log.info("For file: " + excelFile + " Total Number of Rows read: " + totalRowCounter);
            status.setDone();
        }

    }
`
###########################################################################

here is the file
[TA02_Event_basedata_Solid Tumors_v1.3.xlsx](https://github.com/monitorjbl/excel-streaming-reader/files/350331/TA02_Event_basedata_Solid.Tumors_v1.3.xlsx)

**Comment by monitorjbl** [comment]
Took a quick look at your code. It looks like you're trying to read the stream twice, which you do. Once the stream is exhausted, you'll need to open a new one. 

That being said, the library ought to throw a better exception.

**Comment by raboonveeva** [comment]
hey thanks for reply.
i tried to trace back where from this error come. then i saw it came from
`InputStream is = new FileInputStream(excelFile);

        // ########################################### Find sheet and header row ###############################
        for (int i = 0; i < rowLimit && !foundSheet; i++) {
            Workbook workbook = StreamingReader.builder()
                    .rowCacheSize(100)    // number of rows to keep in memory (defaults to 10)
                    .bufferSize(16384)     // buffer size to use when reading InputStream to file (defaults to 1024)
                    .sheetIndex(0)        // index of sheet to use (defaults to 0)
                    .open(is); [# _Eroor GEN_]  
            Sheet  sheet= workbook.getSheetAt(0);
            rowIterator = sheet.iterator();`
could you please be able to specify me where and how did i read stream twice?

**Comment by monitorjbl** [comment]
The stacktrace you posted initially couldn't have come from the line because it has references to my code. Not sure what you're seeing. 

You try to read from the rowIterator twice. After the first read, you exhaust it. On the second read, you should get an exception.

**Comment by raboonveeva** [comment]
yes thank's i understood.
so here is final one

`public static void readExcelFileAsStreamer(File excelFile, List<String> header, Queue<Row> rows, Status status) {

        boolean foundSheet = false;
        int hdrRowPos = -1;
        int sheetPos = -1;        
        int totalRowCounter = 0;        
        Row headerRow = null;
        Sheet  sheet = null;
        try {
            status.init();
            InputStream is = new FileInputStream(excelFile);
            //int i = 0;
            // ########################################### Find sheet and header row ###############################
            Workbook workbook = StreamingReader.builder()
                    .rowCacheSize(100)    // number of rows to keep in memory (defaults to 10)
                    .bufferSize(16384)     // buffer size to use when reading InputStream to file (defaults to 1024)                           
                    .open(is);
            
            
            for (int i = 0; i < workbook.getNumberOfSheets() && !foundSheet; i++) {               
                sheet = workbook.getSheetAt(i);
                log.info("looking at sheet: {}",sheet.getSheetName());                
                for(Row r : sheet){
                    if(foundSheet || r.getRowNum() > HEADER_KEY_POS_MAX)
                        break;                   
                                     
                    
                    if (checkIfHeaderKeyExists(r)) {
                        foundSheet = true;
                        sheetPos = i;
                        headerRow = r;
                        hdrRowPos = r.getRowNum();
                        log.warn("For file: " + excelFile.getName() + " header key is found on Header position: " + hdrRowPos);
                    }
                }
                
            }
            // ############################################################################

            if (hdrRowPos == -1 || sheetPos == -1) {
                throw new IllegalArgumentException("Given File: " + excelFile + " is not a Valid file");
            }

            getHeaders(excelFile, header, headerRow);

            status.setLoadedHeader();
            Thread.sleep(5000);

            int emptyRowCount = 0;

            status.setReading();
            for(Row r : sheet) {
                if(r.getRowNum() <=  hdrRowPos)
                  continue;              

                if (r == null || isEmptyRowStrm(r, header)) {
                    log.warn("For file: " + excelFile + ", row: " + r.getRowNum() + " is empty");
                    emptyRowCount++;
                    if (emptyRowCount > MAX_EMPTY_ROW) {
                        log.warn("finsihed to end of excel file");
                        break;
                    }
                    continue;
                }
                if (r.getRowNum() % 1000 == 0) {
                    // log.info("Added Row: " + r.getRowNum());
                    //Thread.sleep(100);
                }
                if (r != null) {
                    totalRowCounter++;
                    rows.add(r);
                    emptyRowCount = 0;
                }

            }
            Thread.sleep(1000);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            log.info("For file: " + excelFile + " Total Number of Rows read: " + totalRowCounter);
            status.setDone();
        }

    }`

but now i get each row val as null in (Row r : sheet) for the excel file i attached. in first report

**Comment by raboonveeva** [comment]
hey thanks . solved it. my bad.

**Comment by monitorjbl** [comment]
No problem, happy to help!
