### ISSUE TITLE
Can't use foreach or try-with-resources.

### ISSUE THREAD

**Issue by blackdog1987** [monitorjbl/excel-streaming-reader#43]
I followed the ReadMe to code this:
`try (
  InputStream is = new FileInputStream(new File("/path/to/workbook.xlsx"));
  Workbook workbook = StreamingReader.builder()
          .rowCacheSize(100)
          .bufferSize(4096)
          .sheetIndex(0)
          .open(is);
) {
  for (Sheet sheet : workbook){
    System.out.println(sheet.getSheetName());
    for (Row r : sheet) {
      for (Cell c : r) {
        System.out.println(c.getStringCellValue());
      }
    }
  }
}`
I got 2 error. First is that Workbook is not a AutoClosable which is required by try-with-resources. So I can not use in this way. The second problem is that Workbook can't be foreached. 
Then I exclude the org.apache.poi(version 3.9). and use the 3.14. Then it's right now. Seem that the old version can't use the try-with-resources.

**Comment by monitorjbl** [comment]
So, I'm thinking you just had an older version of POI on your classpath. If you use the version that the library references (3.13) or greater, then the examples in README work. [org.apache.poi.ss.usermodel.Workbook](https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Workbook.html) implements both AutoCloseable and Iterable.
