### ISSUE TITLE
StreamingRow.getLastCellNum Is NotSupported

### ISSUE THREAD

**Issue by opticyclic** [monitorjbl/excel-streaming-reader#46]
According to the POI docs you have to use row.getLastCellNum() to iterate properly and take account of missing/blank cells:
https://poi.apache.org/spreadsheet/quick-guide.html#Iterator

However, this is one of the NotSupported operations of StreamingRow

Can you implement this, or alternatively, document how to use the existing implementation to handle blank cells.

**Comment by monitorjbl** [comment]
This is implemented as of 053834bd9bd, it just hasn't been released to Maven Central yet. I'll go ahead and make a release now.

**Comment by monitorjbl** [comment]
Version 1.0.1 is available in Maven Central now, so I'm going to close this issue.
