### ISSUE TITLE
StreamingRow.getFirstCellNum is not supported

### ISSUE THREAD

**Issue by dpogorelov** [monitorjbl/excel-streaming-reader#49]
Hi,

I think it would be correct to implement also the row.getFirstCellNum almost by the same way as you implemented the row.row.getLastCellNum() method in #46 ticket. Here is the possible implementation (if I'm not wrong): 
return (short) (cellMap.size() == 0 ? -1 : 1);

Thx in advance.

**Comment by monitorjbl** [comment]
I don't believe that implementation is correct. You need to return the column number of the first cell in the map. If you'd like to open a PR for this, I'd be happy to review it.

**Comment by dpogorelov** [comment]
Yep, you're right. Sorry for the late answer. Having a look at the XSSFRow.getFirstCellNum():
```
public short getFirstCellNum() {
    	return (short)(_cells.size() == 0 ? -1 : _cells.firstKey());
    }
```
 implementation in the Apache POI we can see that the column number of the first cell should be first key in _cell map. Checking the XSSFRow.getCell(int cellnum) method we can notice that column indexes in the _cell map is 0 based indexes thus in our implementation we should return 0 instead of 1 as the first column index:

`return (short) (cellMap.size() == 0 ? -1 : 1);`

@monitorjbl please correct me if I'm wrong.
