### ISSUE TITLE
Parser removing leading zeros

### ISSUE THREAD

**Issue by hugomarques** [monitorjbl/excel-streaming-reader#5]
So, if you try to parser 0007 as a String instead of a Number you can't right now. Since 0007 matches in the regex number it ll be treated as a number and so it will return 7.
That will be a problem if you are working with ID numbers.

**Comment by monitorjbl** [comment]
I'm not sure what the issue is here, exactly. If you read `0007` as a number, you *should* get `7`. If you read it as a string, you should get `0007`. Java doesn't differentiate between numeric the values `0007` and `7`; they are equivalent.

I wrote a unit test to verify that this works this way, you're welcome to take a look.

**Comment by hugomarques** [comment]
I've created a testCase for this issue.
The problem actually happens with the getCellType method. Even if I format as a String in the xlsx file I'll still receive a Numeric cell. So if my logic depends to discover the type to use the correct get<Type>CellValue() it will break. Example:

if (Cell.CELL_TYPE_STRING == r2.getCell(0).getCellType()) {
 r2.getCell(0).getStringCellValue();
}

Even if I want to consider 007 as a String it will not since the cell type returns Numeric. Maybe that's the expected behaviour for most use cases but I thought it was worth to discuss with you.

https://github.com/hugomarques/excel-streaming-reader/commit/5085e728d5e0ce04ceb58d56f728e4ba59c6af17

**Comment by monitorjbl** [comment]
Ah, I see. I can't get Libre Office to treat that value as anything but numeric. Whenever I type in 0007, it gets automatically converted to 7. The only way I can get it to keep the leading zeros is to put a single quote in front of IT. How did you do it?

**Comment by hugomarques** [comment]
I formatted the cell on excel to be text type or even general.
To solve this issue I'm thinking if does make sense to think only about String types and let the client decide if he should pick as a String or Number.

**Comment by monitorjbl** [comment]
Yeah, I wanted to have some kind of check for cell type. I wasn't able to find any intrinsic property at the time in the XML so I went with a regex check. I can take another look though. 

Regardless, nothing is stopping the user from treating the cell as a number or a string in this case. Both method calls are valid.

**Comment by monitorjbl** [comment]
Found a solution that appears to work for this. I've added your type checks to my unit test. Can you take a look and see if it's working for you as well?
