### ISSUE TITLE
StreamingCell.getBooleanCellValue( ) is dangerous

### ISSUE THREAD

**Issue by gredler** [monitorjbl/excel-streaming-reader#54]
This library is very nice in that it provides an easy drop-in replacement for simple uses of the vanilla POI API. One important part of this ease-of-use is that unimplemented features are reported very obviously at runtime via e.g. `NotSupportedException`s. If you try this library with your existing code and you don't get any exceptions at runtime, you're probably OK.

Unfortunately, `StreamingCell.getBooleanCellValue()` breaks this convention and assumption by not being implemented, but rather than throwing an exception it simply returns `false`. If users are not very, very careful, this could encourage them to start using this library when in fact it doesn't implement functionality that they need.

I don't know if `StreamingCell.getBooleanCellValue()` can be implemented or not; if it can, then it would be great to see it implemented; if it can't be implemented, then throwing a `NotSupportedException` would be more appropriate than just returning `false`.

https://github.com/monitorjbl/excel-streaming-reader/blob/master/src/main/java/com/monitorjbl/xlsx/impl/StreamingCell.java#L305

**Comment by monitorjbl** [comment]
Good catch! I was actually just in the middle of reviewing #50 when you opened this issue. I just merged it, so the next release will support ` getBooleanCellValue()`

**Comment by gredler** [comment]
Ah, nice -- thanks so much!
