### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by AZhiKai** [monitorjbl/excel-streaming-reader#57]
Hi there! Just want to thank you for this library, it's exactly what I needed.

But to get started, can I clarify that ontop of including the .jar file in the libs folder, I also need to include poi-3.13.jar from Apache POI? Otherwise, classes like Workbook couldn't be resolved. 

While waiting for an answer, my libs folder contains the following 2 jar files. 

`xlsx-streamer-1.0.0 and poi-3.13
`

Upon running my project, I encountered the following error. 

`java.lang.ClassNotFoundException: Didn't find class "org.slf4j.LoggerFactory"`

After adding the respective slf4j jar file according to the dependency stated in the Logging section of your README, the next error regarding log4j appears.

May I know where did I went wrong? I would appreciate if you could guide me through the proper setup and files needed in order to get this library working.

Much appreciated and many thanks in advance!

**Comment by monitorjbl** [comment]
Sorry for taking so long to answer this, I got married in October and then the holidays kind of torpedoed my free time for a while. If you're not using a package manager like Maven or Gradle (and you really, *really* should be), you'll have to evaluate the entire transitive dependency set and make sure everything is in the classpath. Here's the output of `mvn dependency:tree` for the latest version of the code:

```
[INFO] com.monitorjbl:xlsx-streamer:jar:1.0.1
[INFO] +- org.apache.poi:poi-ooxml:jar:3.13:compile
[INFO] |  +- org.apache.poi:poi:jar:3.13:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  \- org.apache.poi:poi-ooxml-schemas:jar:3.13:compile
[INFO] |     \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] |        \- stax:stax-api:jar:1.0.1:compile
[INFO] +- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.6:compile
```

If any of these dependencies are not present, the library may or may not work. Java loads classes on-demand, so its possible that it will work without one or more of these JARs as long as the particular bit of code referencing a class in a missing JAR is never reached.

I'm going to close this as it's not actually a bug with the library, but if you have any other questions I'll try to answer them here.
