### ISSUE TITLE
License

### ISSUE THREAD

**Issue by martonp** [monitorjbl/excel-streaming-reader#6]
Hi, 

I am currently an intern working at a company, and I really like your library. I would like to use your library in a commercial web app, but if I use it using the license you are currently using, then I would be required to share the source code. This wouldn't make any sense because it would be a security issue for the site. I was wondering if you could release it under the Lesser General Public License. I would really appreciate it. 

Thanks!

**Comment by monitorjbl** [comment]
Glad to hear you like the library! Let me do a bit of research and get back to you.

**Comment by martonp** [comment]
After doing more research I realized that the license is fine for web apps because the product isn't being distributed. 
Thanks anyways!

**Comment by monitorjbl** [comment]
Ah, that makes things simple! Out of curiosity, can you tell me what app you're using it in?

**Comment by martonp** [comment]
I'm using it to go through large excel files containing tax data and checking that the right information is in each row.

**Comment by monitorjbl** [comment]
Cool! Well, I hope that goes well for you and if you run into any bugs feel free to open an issue here. I'll try and get them fixed for you, and you're always welcome to open a pull request!
