### ISSUE TITLE
StreamingWorkbook doesn't support getName

### ISSUE THREAD

**Issue by neal001** [monitorjbl/excel-streaming-reader#63]
Hi all,
  Can you implement the "Name" part function?  eg. getName...
  Or can you give some suggestions for it?
  thank you.

**Comment by monitorjbl** [comment]
Can you give me an example of how you would use this method while reading? The examples I've found only work on writes, which this library explicitly does not support.

**Comment by monitorjbl** [comment]
Closing because this library does not support writing.
