### ISSUE TITLE
The supplied data appears to be in the OLE2 Format

### ISSUE THREAD

**Issue by ElsayedAwdElsayed** [monitorjbl/excel-streaming-reader#66]
> org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException: The supplied data appears to be in the OLE2 Format. You are calling the part of POI that deals with OOXML (Office Open XML) Documents. You need to call a different part of POI to process this data (eg HSSF instead of XSSF)

I got this exception  when I loaded file of type XLS 

**and this is my code** 

> File inputWorkbook inputWorkbook = new File(fileName);
> Streaming reader reader = StreamingReader.builder()
>                     .rowCacheSize(100)   
>                     .bufferSize(4096)    
>                     .sheetIndex(0)        
>                     .read(inputWorkbook);

**Comment by monitorjbl** [comment]
XLS is not supported by this library. It cannot be streamed because the format is not XML. It's some custom format Microsoft came up with back in the 90s.
