### ISSUE TITLE
Request for release 1.0.2

### ISSUE THREAD

**Issue by ms1111** [monitorjbl/excel-streaming-reader#68]
Hi Taylor,

There have been a few fixes merged since 1.0.1 (#50 #56 #61 #65) and I would quite selfishly like to get rid of my git submodule and go back to pulling a release from Maven Central. Would you be willing to push a release? Let me know if there's anything I can do to help.

Thanks,
MIke

PS: Thanks for publishing this library. It really saved my weekend when I found it back in October. More likely, many weekends.

**Comment by monitorjbl** [comment]
This was released today, it should be available on Maven Central by tomorrow morning.
