### ISSUE TITLE
Slow When reading more than 65000 records with 10 columns.

### ISSUE THREAD

**Issue by MRabindra10** [monitorjbl/excel-streaming-reader#69]
65000 reads in 594 milisecs but for 130000 records it takes 4782 milisecs

record * 2 times takes around time * 7 times.

**Comment by monitorjbl** [comment]
There are a lot of factors that can contribute to this, so I don't have enough information from your issue. Can you provide an example spreadsheet, the full set of JVM options you used, and a description of what your application does?

**Comment by MRabindra10** [comment]
Hi Jones,

Thanks for your response. below is the code. you can use any sample data
spreadsheet with string, numbers in cells.

Could you tell me what is the reason the reading process is slow. you can
use two sheets in one file.

public class testMain {

public static void main(String[] args) throws IOException {
File file = new
File("D:/testRoc3_3/DataDir/filecollection/LAPORAN_CASHOUTASD_45 -
Cs.xlsx");
AbstractXLSByteBufferL buffer = new XLSXByteBufferL(file);
//AbstractXLSByteBufferL buffer = new XLSByteBufferL(file);

long starttime = System.currentTimeMillis();
while (buffer.hasNext()) {
buffer.next();
}
long endtime = System.currentTimeMillis();
System.out.println(endtime-starttime);
}
}


public class XLSXByteBufferL extends AbstractXLSByteBufferL {

InputStream is = null;
Workbook workbook = null;
Sheet sheet = null;
private int sheetId = 0;
boolean isDataSheet = false;
boolean isEmptyRow = true;

Iterator<Sheet> sheetIterator;
Iterator<Row> rowIterator;

public XLSXByteBufferL(File file) throws IOException {
super(-1, 0, file.length(), file.length());
initialize(file);
}

private void initialize(File file) throws IOException {
try {
is = new FileInputStream(file);
}catch (FileNotFoundException e) {
e.printStackTrace();
}
this.workbook = StreamingReader.builder()
   .rowCacheSize(100000)    // number of rows to keep in memory (defaults
to 10)
   .bufferSize(4098)      // buffer size to use when reading InputStream to
file (defaults to 1024)
   .open(is);   // index of sheet to use (defaults to 0)

sheetIterator = workbook.iterator();
if(sheetIterator.hasNext()){
sheet = sheetIterator.next();
idvsSheetName.put(sheetId++, sheet.getSheetName());
this.isDataSheet = true;
}
rowIterator = sheet.iterator();
}

public boolean hasNext() {

if(this.rowIterator.hasNext())
return true;
else if(this.sheetIterator.hasNext()){
sheet = sheetIterator.next();
idvsSheetName.put(sheetId++, sheet.getSheetName());
rowIterator = sheet.iterator();
this.isDataSheet = true;
return true;
}
else{
return false;
}
}

public void next() {

if (!this.fetchNext)
return;

colIndexVsField.clear();
this.colPos = 0;

if (this.isDataSheet) {
            if (!this.isLastRow) {
                colIndexVsField.put((short) 0,
this.idvsSheetName.get(this.readSheetId++));
                this.rowId = 0;
                this.isCurrentRowHasSheet = true;
            } else {
            colIndexVsField.put((short) 0,
this.idvsSheetName.get(this.readSheetId++));
                this.currentRowId = this.rowId;
                this.rowId = -1;
                this.isLastRow = false;
                this.isCurrentRowHasSheet = false;
            }
            this.isDataSheet = false;
            return;
        }

Row row = this.rowIterator.next();
isEmptyRow = true;
Iterator<Cell> cellIterator = row.cellIterator();

while (cellIterator.hasNext()) {
Cell cell = cellIterator.next();

if (cell == null)
return;
switch (cell.getCellType()) {

case Cell.CELL_TYPE_NUMERIC:
Object value = Double.valueOf(cell.getNumericCellValue());
if(DateUtil.isCellDateFormatted(cell)){
value = DateUtil.getJavaDate((Double)value);
}
else{
StreamingCell streamingCell = (StreamingCell)cell;
String stringFormat = streamingCell.getNumericFormat();
if(stringFormat.equals("@"))
value = String.valueOf(value);
}

isLastRow = true;

this.currentRowId = rowId;
rowId = cell.getRowIndex();

if (isCurrentRowHasSheet) {
isCurrentRowHasSheet = false;
rowId = cell.getRowIndex();
}
this.isSheet = false;
maxColPos = cell.getColumnIndex();
colIndexVsField.put((short) cell.getColumnIndex(), value);
isEmptyRow = false;
break;

case Cell.CELL_TYPE_STRING:
isLastRow = true;

this.currentRowId = rowId;
rowId = cell.getRowIndex();
if (isCurrentRowHasSheet) {
isCurrentRowHasSheet = false;
rowId = cell.getRowIndex();
}
this.isSheet = false;
maxColPos = cell.getColumnIndex();
colIndexVsField.put((short) cell.getColumnIndex(),
cell.getStringCellValue());
isEmptyRow = false;
break;

case Cell.CELL_TYPE_BOOLEAN:
isLastRow = true;
this.currentRowId = rowId;
rowId = cell.getRowIndex();
if (isCurrentRowHasSheet) {
isCurrentRowHasSheet = false;
rowId = cell.getRowIndex();
}
this.isSheet = false;
maxColPos = cell.getColumnIndex();
colIndexVsField.put((short) cell.getColumnIndex(),
cell.getBooleanCellValue());
isEmptyRow = false;
break;

case Cell.CELL_TYPE_FORMULA:
isLastRow = true;
this.currentRowId = rowId;
rowId = cell.getRowIndex();

if (isCurrentRowHasSheet) {
isCurrentRowHasSheet = false;
rowId = cell.getRowIndex();
}
this.isSheet = false;
maxColPos = cell.getColumnIndex();
colIndexVsField.put((short) cell.getColumnIndex(),
cell.getBooleanCellValue());
isEmptyRow = false;

break;
}
}
if(isEmptyRow && rowIterator.hasNext()){
next();
}
if(!rowIterator.hasNext())
{
this.isSheet = true;
}
return;
}
public boolean isNullRow() {
return false;
}
}


Thanks,
M Rabindra

**Comment by monitorjbl** [comment]
I need an example *spreadsheet*, not your code. I can't reproduce this behavior without the data you are reading in.

**Comment by MRabindra10** [comment]
Hi,

Here is the sample spreadsheet. first read with one sheet of 65000 record.
then copy first sheet and create new sheet paste there. and try to read two
sheet of 130000 records. and see the difference of timing.

Thanks,
M Rabindra

**Comment by monitorjbl** [comment]
You need to attach the spreadsheet to the issue. Here is a guide: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/. It looks like you're using email to reply to me and I don't think adding it as an email attachment works.

**Comment by MRabindra10** [comment]
[testfile.xlsx](https://github.com/monitorjbl/excel-streaming-reader/files/710107/testfile.xlsx)

Hi,

Here is the sample spreadsheet. first read with one sheet of 65000 record.
then copy first sheet and create new sheet paste there. and try to read two
sheet of 130000 records. and see the difference of timing.

Thanks,
M Rabindra

**Comment by MRabindra10** [comment]
[test2.xlsx](https://github.com/monitorjbl/excel-streaming-reader/files/711187/test2.xlsx)

Here is the sample spreadsheet. first read with one sheet of 65000 record.
then copy first sheet and create new sheet paste there. and try to read two
sheet of 130000 records. and see the difference of timing.

**Comment by kakadikrishna** [comment]
I too not able read large excel files with 1 million rows, I am getting `java.lang.OutOfMemoryError: Java heap space`

I am not able attach my excel file which is around 34MB( getting errror `Yowza that's a big file. Try again with a file smaller than 10MB`)

**Comment by monitorjbl** [comment]
@kakadikrishna I cannot replicate your issue in isolation. I can verify that up to 194,000 rows can be read in just under **20 seconds** using no more than **16MB of memory**. This is only 20% of the 1 million rows you're reporting but with any reasonable amount of application memory, you shouldn't have any problems.

Proof:
![image](https://cloud.githubusercontent.com/assets/1149136/22235277/95486756-e1cc-11e6-812a-00b7fe4f8a5c.png)

No information is saved from the spreadsheet, the test is purely to prove that the library does not have a memory leak. I strongly suspect that your application is retaining data from the rows and *that* is what is causing your OOM error. It's up to you to dig into that, this library can't stop you from retaining too much data, it just streams spreadsheet data with very little memory footprint.

**Comment by monitorjbl** [comment]
@MRabindra10 It consistently takes my computer around 5-5.5 seconds to read 64800 rows. Subsequent reads are slightly faster, averaging about 3.5 seconds (most likely due to the lack of classloading required). Given the volume of data to be processed, I seriously doubt it will ever be able to completely read in under 1 second. As you can see, 1.3 seconds is spent just by the SAX parser to read elements out of the stream in the run on your data:

![image](https://cloud.githubusercontent.com/assets/1149136/22235643/d3f1f830-e1ce-11e6-9997-00e6988c7726.png)

I'm not entirely sure what's going on with your environment, but are you sure that the code to read even executes on the 594ms execution? It's streaming data after all, so if you try to re-use the reader after reading it you will run into issues.
