### ISSUE TITLE
Support 1904-based date values

### ISSUE THREAD

**Issue by dgriffith** [monitorjbl/excel-streaming-reader#71]
Date cells are currently evaluated assuming 1900-based date values.  Older sheets created by Excel for Mac and newer sheets created by exporting from Numbers use 1904 based dates.  Evidently there's a flag at the workbook level that can distinguish these, but it is currently ignored.  Compare the calculations in getDateCellValue between com.monitorjbl.xlsx.impl.StreamingCell and org.apache.poi.xssf.usermodel.XSSFCell streaming value.  

If fixing this is too much effort, I'd be happy to contribute a fix myself, but would love any insights you might have to offer on how to start such work.

Reference: https://support.microsoft.com/en-us/help/214330/differences-between-the-1900-and-the-1904-date-system-in-excel

**Comment by monitorjbl** [comment]
Fixed by #74
