### ISSUE TITLE
Not able read large excel files with 1 million rows

### ISSUE THREAD

**Issue by kakadikrishna** [monitorjbl/excel-streaming-reader#73]
Not able read large excel files with 1 million rows, I am getting java.lang.OutOfMemoryError: Java heap space

I am not able attach my excel file which is around 34MB( getting errror Yowza that's a big file. Try again with a file smaller than 10MB)

Below is the sample data in the Excel, where first row is header followed by 1 million employee records
Code	FirstName	LastName	City	Address	Country	DepartmentRef	PersonTypeRef	PropertyRef
A1000001	A1000001	A1000001	Hyderabad	1stAvenue	India	99	Internal coordinator	26
A1000002	A1000002	A1000002	Hyderabad	1stAvenue	India	99	Internal coordinator	26
A1000003	A1000003	A1000003	Hyderabad	1stAvenue	India	99	Internal coordinator	26

**Comment by monitorjbl** [comment]
@kakadikrishna I cannot replicate your issue in isolation. I can verify that up to 194,000 rows can be read in just under **20 seconds** using no more than **16MB of memory**. This is only 20% of the 1 million rows you're reporting but with any reasonable amount of application memory, you shouldn't have any problems.

Proof:
![image](https://cloud.githubusercontent.com/assets/1149136/22235277/95486756-e1cc-11e6-812a-00b7fe4f8a5c.png)

No information is saved from the spreadsheet, the test is purely to prove that the library does not have a memory leak. I strongly suspect that your application is retaining data from the rows and *that* is what is causing your OOM error. It's up to you to dig into that, this library can't stop you from retaining too much data, it just streams spreadsheet data with very little memory footprint.

**Comment by kakadikrishna** [comment]
I tried standalone program, i got same error, below is the code snippet
`  	InputStream is = new FileInputStream(new File("C:\\KAKADI_BACKUP\\Cusotmer calls\\TK-1144\\TestpersonImport_1Million.xlsx"));
    Workbook workbook = StreamingReader.builder().rowCacheSize(100) // number of rows to keep in memory (defaults to 10)
                                       .bufferSize(4096) // buffer size to use when reading InputStream to file (defaults to 1024)
                                       .open(is); // InputStream or File for XLSX file (required)
    Sheet sheet = workbook.getSheetAt(0);
    int noOfRows = 0;

    System.out.println(sheet.getSheetName());
    for (Row r : sheet)
    {
      for (Cell c : r)
      {
        System.out.println(" " + c.getStringCellValue());
        noOfRows++;
      }
    }
    System.out.println("Total Number of rows: " + noOfRows);`

**Comment by monitorjbl** [comment]
If you're getting an exception with this snippet then there is something very exceptional about your spreadsheet. Based on that config, you would have to blow the heap in **under 100 rows**. How much data is in each row?

**Comment by kakadikrishna** [comment]
Excel only have 9 columns, I also included sample above. 
I however could process 35000 rows successfully

**Comment by monitorjbl** [comment]
Can you post the full stacktrace you get?

**Comment by kakadikrishna** [comment]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.resize(Saver.java:1700)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.preEmit(Saver.java:1303)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.emit(Saver.java:1190)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.emitElement(Saver.java:962)
	at org.apache.xmlbeans.impl.store.Saver.processElement(Saver.java:476)
	at org.apache.xmlbeans.impl.store.Saver.process(Saver.java:307)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.saveToString(Saver.java:1864)
	at org.apache.xmlbeans.impl.store.Cursor._xmlText(Cursor.java:546)
	at org.apache.xmlbeans.impl.store.Cursor.xmlText(Cursor.java:2436)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.xmlText(XmlObjectBase.java:1500)
	at org.apache.poi.xssf.model.SharedStringsTable.getKey(SharedStringsTable.java:134)
	at org.apache.poi.xssf.model.SharedStringsTable.readFrom(SharedStringsTable.java:124)
	at org.apache.poi.xssf.model.SharedStringsTable.<init>(SharedStringsTable.java:106)
	at org.apache.poi.xssf.eventusermodel.XSSFReader.getSharedStringsTable(XSSFReader.java:82)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:104)
	at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:80)
	at com.monitorjbl.xlsx.StreamingReader$Builder.open(StreamingReader.java:228)
	at nl.planon.morpheus.pnworkers.server.excelworker.excel.TestExcelReader.readExcel(TestExcelReader.java:45)
	at nl.planon.morpheus.pnworkers.server.excelworker.excel.TestExcelReader.main(TestExcelReader.java:25)

**Comment by monitorjbl** [comment]
Ah, well that explains it. Your data has an extremely high cardinality so the SharedStringsTable is blowing up the heap. This is going to be a complex issue to solve. The SST is referenced by the Sheet XML and is necessary to get Cell values out of it. Because of this, it *must* be loaded fully before anything else can happen. 

The only option I see to maintain compatibility is to make a custom implementation of this class and force it to use a disk-backed store. This will have serious performance implications,  but it's the only way to keep memory usage down.

**Comment by monitorjbl** [comment]
@kakadikrishna I added an experimental option to buffer the SST data. This should help with your issue; the SST is loaded into a file-backed list that is accessed on-demand by the library. By doing this, no more than a very small portion of memory is used to contain the SST data. To enable it, simply add this to your builder:

```
 InputStream is = new FileInputStream(new File("test.xlsx"));   
Workbook wb = StreamingReader.builder()   
    .sstCacheSize(100)    
    .open(is); 
```

The trade-off here is performance and some disk space, typically on the order of a few dozen MB. If you enable this option, all reads of SST data will incur a disk read penalty (unless caught by the cache). This is undesirable in most cases, but if you have a truly massive dataset with very unique entries you can use this.

To give you some sense of the performance of this test. I was able to run the code below with **64mb** of heap in about **16 seconds**. The test data has **1 million rows** and **10 columns**, and each cell had a random 32-character string in it.

```
public void testPerformance() throws Exception {    
  long start = System.currentTimeMillis();    
  try(    
      InputStream is = new FileInputStream(new File("test.xlsx"));   
      Workbook wb = StreamingReader.builder()   
          .sstCacheSize(100)    
          .open(is);    
  ) {   
    Sheet sheet = wb.getSheetAt(0);   
    long count = 0;   
    for(Row row : sheet) {    
      count++;    
    }   
    System.out.println("Read "+count+" rows in "+(System.currentTimeMillis() - start)+"ms");    
  }   
}
```

If you'd like to try this out, clone the latest code out of the master branch and install the library locally.

**Comment by kakadikrishna** [comment]
it works thank you

**Comment by indrajeetgour** [comment]
Hey @monitorjbl would you please tell what you have used for this performance graphs charts show.

**Comment by monitorjbl** [comment]
They're from YourKit, a Java profiler.

**Comment by davidw76** [comment]
is sstCacheSize still a supported option? I am running in to an out of memory error with large files

**Comment by rambabu14** [comment]
Hi @monitorjbl, From where StreamingReader Object comming, can you tell me the jar file name..

**Comment by Chandan1si13is016** [comment]
@monitorjbl 
` InputStream is = new FileInputStream(new File("test.xlsx"));   
      Workbook wb = StreamingReader.builder()   
          .sstCacheSize(100)    
          .open(is);    `

I am not able to convert StreamingReader to Workbook. 
can you please inform me why?

**Comment by Shoojan** [comment]
@Chandan1si13is016 @rambabu14 
It's using Excel Streaming Reader. 
The link's given below: 
https://github.com/monitorjbl/excel-streaming-reader

**Comment by enghelab** [comment]
@kakadikrishna can you read large excel file , finaly ?

**Comment by kakadikrishna** [comment]
yes I could

**Comment by enghelab** [comment]
java.lang.NoClassDefFoundError: Could not initialize class com.monitorjbl.xlsx.StreamingReader
I used this library correctly !
What should I do ?
What is this error ?

**Comment by enghelab** [comment]
@kakadikrishna 
I used this library correctly !
 java.lang.NoClassDefFoundError: Could not initialize class com.monitorjbl.xlsx.StreamingReader
What should I do ?
What is this error ?
