### ISSUE TITLE
Cannot read really big excel file

### ISSUE THREAD

**Issue by alusbars** [monitorjbl/excel-streaming-reader#95]
Hi guys,

I've generated .xlsx file with apache poi SXSSF 
number of sheets : 1;
number of rows: 1 million; 
number of cells in each row: 600. 

I read this file with Streaming Reader with next options:
rowCacheSize 10,100,1000
buffersize 4096-8192

I'm using 
xlsx-streamer 1.1.0
apache poi 3.15

I'm iterating through xlsx file with this simple code:

`Iterator<Row> rowIterator = sheet.rowIterator();
while (rowIterator.hasNext()) {
Row row = rowIterator.next();
...
}`

At ~ 15500 row number rowIterator.next() raises exception:

`Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.next(StreamingSheetReader.java:347) `

I'll appreciate for any help. 

Please, see the attached idea project 
[filegeneratortest.zip](https://github.com/monitorjbl/excel-streaming-reader/files/1013844/filegeneratortest.zip)

**Comment by monitorjbl** [comment]
Wow, this is a new one to me. Apparently you're hitting this and its causing the rowCache to not be updated completely:

```
2017-05-20 18:54:53,118 [com.monitorjbl.xlsx.impl.StreamingSheetReader] DEBUG: End of stream
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[309828,18539]
Message: Zip bomb detected! The file would exceed the max size of the expanded data in the zip-file. This may indicates that the file is used to inflate memory usage and thus could pose a security risk. You can adjust this limit via ZipSecureFile.setMaxEntrySize() if you need to work with files which are very large. Counter: 4294970522, cis.counter: 374784000Limits: MAX_ENTRY_SIZE: 4294967295
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
	at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.getRow(StreamingSheetReader.java:77)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.access$100(StreamingSheetReader.java:38)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.hasNext(StreamingSheetReader.java:366)
	at com.monitorjbl.xlsx.Test.iterateThrough(Test.java:105)
	at com.monitorjbl.xlsx.Test.main(Test.java:30)
```

It's being swallowed so you don't see that, even with debug logging enabled. What is *supposed* to happen is the hasNext() call should return false, but it appears that it isn't. I'm going to make sure the logging includes the exception that caused the parse failure and make sure hasNext() returns false in this case. 

I'm not sure what you'll need to do to read this particular Excel sheet though. The error is coming out of SAX, not this library.

**Comment by monitorjbl** [comment]
It looks like setting `ZipSecureFile.setMaxEntrySize()` will work, it's a static method that you can set in your code. I'm not going to include that call as part of this library because it has external effects within the JVM; for instance, if you are also reading other ZIP files in your application you might want to set this independently to avoid security issues.

**Comment by monitorjbl** [comment]
Looks like this is actually a known issue in POI: https://bz.apache.org/bugzilla/show_bug.cgi?id=58499. The workaround they suggest is to add this line before you open the workbook:

`ZipSecureFile.setMinInflateRatio(0);`

**Comment by monitorjbl** [comment]
Boy, did this ever send me down a rabbit hole. Bad news, though: I kept digging and this does not work in POI 3.16.

The reason for that is a change to the `ZipSecureFile` class made in 3.14 that makes a check for MAX_ENTRY_SIZE. In 3.14+, it is locked to a [max of 4GB](https://github.com/apache/poi/blob/REL_3_14_FINAL/src/ooxml/java/org/apache/poi/openxml4j/util/ZipSecureFile.java#L120) and the check is made [before anything else](https://github.com/apache/poi/blob/REL_3_14_FINAL/src/ooxml/java/org/apache/poi/openxml4j/util/ZipSecureFile.java#L234). In 3.13, this check was made *after* the MIN_INFLATE_RATIO was [taken into account](https://github.com/apache/poi/blob/REL_3_13_FINAL/src/ooxml/java/org/apache/poi/openxml4j/util/ZipSecureFile.java#L192) so it was possible to have larger values. This is no longer true; the POI team apparently made the decision that no worksheet will ever be larger than 4GB :(.

I'd encourage you to open a defect against this in the Apache bugtracker. There's nothing that can currently be done to support your use case unless you downgrade to an older version of this library that supports POI 3.13.
